### ISSUE TITLE
Update Comment

### ISSUE THREAD

**Issue by BradSherwood24** [TastySatang/aprilMod6GroupProject#14]
As an authorized user I would like to edit a comment on an event
By clicking on edit comment button next to my comment to show a update form
On successful edit I want the comment to be edited, and the form to disappear
On an unsuccessful attempt, I would like errors of the form to be listed to correct the errors and forms to be prepopulated with existing values

**Comment by TastySatang** [comment]
clicking edit comment shows an update form, successful edit changes the comment organically.

No need for errors.
