### ISSUE TITLE
Update Event

### ISSUE THREAD

**Issue by BradSherwood24** [TastySatang/aprilMod6GroupProject#7]
As an authorized user, I want to be able to update events that belong to me
By clicking an update button only shown to me on the event page
It should redirect me to an update form prepopulated with the current values
On successful submit I want to be redirected to the events page
On unsuccessful event update attempt, I Would like errors of the form to be listed to correct and the forms to be prepopulated with previous attempt

**Comment by TastySatang** [comment]
update event possible on single update page. Does not redirect to another page to show form.
